receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp/elastic:
    endpoint: "apm-server:8200"
    tls:
      insecure: true
  logging:

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
      processors: [batch]
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
      processors: [batch]
